### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [derekcsm/hubble_gallery#30]
Here's how to: https://f-droid.org/contribute/

**Comment by derekcsm** [comment]
Cool, thanks for the heads up! I'll definitely add it when I get some time to work on this again.

**Comment by est31** [comment]
I've added it to f-droid today: https://gitlab.com/fdroid/fdroiddata/commit/2362b7b5

One minor question towards you as upstream: crashlytics is not allowed on f-droid as it is proprietary, and I had to patch out its use for this release. It would be best if future releases could add a fdroid gradle flavour so that the patching out process doesn't have to be repeated. Thanks!

**Comment by derekcsm** [comment]
@est31 Thank you! 😄 This is great, I'm really glad it's up on there. When I get some time I'll start a branch to have an f-droid specific flavor and will be sure to add that in whenever the next release comes out.
